Local rebuild
k8-proxy/k8-traffic-generator pull request #100
Opened 2020-09-13 16:58 UTC by yardenshoham

Closes #83

2020-09-15 00:25 UTC, DinisCruz requested changes
@yardenshoham please remove and invalidate these AWS keys

2020-09-15 00:25 UTC, DinisCruz commented on upwork-devs/yarden-shoham/local-rebuild/dispatcher/Dockerfile
> +    SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG \
Hi, which secret key is this?

2020-09-15 00:25 UTC, DinisCruz commented on upwork-devs/yarden-shoham/local-rebuild/dispatcher/README.md
> +| `SECRET_KEY`         | S3 secret key    | `zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG`           |
Same here, we can’t put AWS keys on GitHub

2020-09-15 00:25 UTC, DinisCruz commented on upwork-devs/yarden-shoham/local-rebuild/downloader/Dockerfile
> +    SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG \
Another secret key

2020-09-15 00:25 UTC, DinisCruz commented on upwork-devs/yarden-shoham/local-rebuild/downloader/README.md
> +| `ACCESS_KEY`         | S3 access key                                  | `Q3AM3UQ867SPQQA43P2F`                             |
And here

2020-09-15 08:16 UTC, yardenshoham commented
All of these are the default credentials to min.io's default S3. They are not AWS secrets. They're simply demo values. See https://docs.min.io/docs/minio-client-complete-guide.html.

![image](https://user-images.githubusercontent.com/20454870/93184308-bd0ffd80-f744-11ea-9ab6-a3805eb9972f.png)

> `mc` is pre-configured with https://play.min.io, aliased as "play". It is a hosted MinIO server for testing and development purpose.

2020-09-17 23:34 UTC, DinisCruz approved these changes
Ok, but the security team should pickup these keys

2020-09-17 23:34 UTC, merged