fix bandit issues
k8-proxy/k8-traffic-generator pull request #131
Opened 2020-09-23 06:00 UTC by pranaysahith

2020-09-23 13:01 UTC, yardenshoham requested changes
One issue left
```
>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
   Severity: Medium   Confidence: High
   Location: ./upwork-devs/pranay-sahith/opencensus_poc/traffic_generator.py:34
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen
33	            req = urllib.request.Request(url)
34	            with urllib.request.urlopen(req) as f:
35	                log.info(f"downloading pdf: {url}")
```

2020-09-25 07:41 UTC, yardenshoham approved these changes
Awesome, thanks!

2020-09-25 07:42 UTC, yardenshoham commented
With #134 and this merged, we'll pass the scan.

2020-09-26 21:58 UTC, DinisCruz approved these changes

2020-09-26 21:58 UTC, merged